# GitHub workflow
name: Create and Publish package

on:
  push:
    branches: [ master ]

# https://github.com/marketplace/actions/publish-nuget

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    name: build, pack & publich
    runs-on: ububtu-latest
    steps:   
    
      - name: create version
        run: echo "Version: 0.1"

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
      
      - name: Publish 
        id: publich
        uses: rohith/publish-nuget@v2.5.0
        with:
          PROJECT_FILE_PATH: MongoDB/MongoDB.csproj
          PACKAGE_NAME: Alex75.Common.MongoDB
          # VERSION_REGEX: <Version>(.*)<\/Version>
          VERSION_STATIC: 0.1.0-alpha
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # NUGET_SOURCE: https://api.nuget.org



    # The type of runner that the job will run on
    #runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2

    # Runs a single command using the runners shell
    #- name: Run a one-line script
    #  run: echo Hello, world!

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.

